### ISSUE TITLE
Error message with pm.ttest

### ISSUE THREAD

**Issue by frederic-santos** [jjlynch2/OsteoSort#49]
On line 138, the following instruction:
`clusterExport(cl, list("ref", "alphalevel", "p1", "absolutevalue", "testagainstzero", "output_options", "tails", "is.uniquepm", "unique.difsd", "unique.difm", "unique.df", "unique.ycol", "unique.yrow", "unique.difa", "unique.boxcox"), envir = environment())`
produces an error message because the argument "p1" is undefined and cannot be found elsewhere in the code.

(This problem also triggers an error in OsteoShiny for pair-matching, and the app crashes.)

**Comment by jjlynch2** [comment]
I've updated the master branch with a fix for this. Try the following to install OsteoSort from the master branch (install_github("jjlynch2/OsteoSort"), and let me know if this resolves the problem.

**Comment by frederic-santos** [comment]
It works perfectly now, thank you! ;)
